In [1]:
import torch

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
torch.tensor([[1,2,3], [4,5,6]]).shape

torch.Size([2, 3])

In [7]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = w * x + b
# Compute derivatives
y.backward()
# Display gradients
print('dy/dx (as No requires_grad is true hence none):', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx (as No requires_grad is true hence none): None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [8]:
torch.full((5, 4), 10)

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]])

In [9]:
# cat, sin, reshape - all are present

In [10]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [11]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

Autograd: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
GPU support: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.

# Linear-regression from scrach using pytorch

In [13]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [14]:
# Targets (apples, oranges)
target = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [15]:
#Convert input and target to tensors
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

print(inputs,"\n")
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [16]:
# weights and biases
w = torch.randn(2,3 , requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w)
print(b)

tensor([[-1.6331,  0.9302,  0.0610],
        [ 0.7816,  0.7310, -0.9758]], requires_grad=True)
tensor([0.7106, 0.9738], requires_grad=True)


In [21]:
def model(x):
  return x @ w.t() + b  # w.t() transpose

In [22]:
preds = model(inputs)
print(preds)

tensor([[ -53.5587,   65.0460],
        [ -62.1391,   73.9736],
        [ -13.1845,  110.3258],
        [-123.6084,   76.0236],
        [ -18.4038,   56.7718]], grad_fn=<AddBackward0>)


In [24]:
# loss function MSE
def MSE(actual, target):
  diff = actual - target
  return torch.sum(diff * diff) / diff.numel()

In [25]:
loss = MSE(target, preds)
print(loss)

tensor(9256.9619, grad_fn=<DivBackward0>)


In [26]:
loss.backward()

In [27]:
print(w, "\n")
print(w.grad)

tensor([[-1.6331,  0.9302,  0.0610],
        [ 0.7816,  0.7310, -0.9758]], requires_grad=True) 

tensor([[-11150.4834, -11113.0645,  -7084.8809],
        [ -1021.4073,  -2008.8955,  -1233.9830]])


In [28]:
print(b, "\n")
print(b.grad)

tensor([0.7106, 0.9738], requires_grad=True) 

tensor([-130.3789,  -15.5718])


In [29]:
#reset grad
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [35]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'torchvision'

In [ ]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)