In [1]:
import tensorflow as tf
from tensorflow import keras

print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
# print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.13.0
Eager execution is: True


In [2]:
if tf.test.is_gpu_available():
    print('Running on GPU')
else:
    print('Running on CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Running on CPU


In [3]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
tf.config.list_physical_devices('GPU')

[]

In [5]:
ankit = tf.constant(42) 
ankit

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
ankit.numpy()

42

In [7]:
ankit.dtype

tf.int32

In [8]:
ankit1 = tf.constant(1, dtype = tf.int64)
ankit1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [9]:
ankit2 = tf.constant([[4,2],[9,5]])
ankit2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]])>

In [10]:
print(tf.ones(shape = (2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [12]:
const2 = tf.constant([[3,4,5], [3,4,5]])
const1 = tf.constant([[1,2,3], [1,2,3]])
result = tf.add(const1, const2)

print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


In [13]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.4968039 , -0.05255138],
       [-0.40238965,  1.2697452 ]], dtype=float32)>

In [14]:

# Creating a variable with an initial value
initial_value = [0.1, 0.2, 0.3]
variable_tensor = tf.Variable(initial_value)

# Updating the variable's value
new_value = [0.4, 0.5, 0.6]
variable_tensor.assign(new_value)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([0.4, 0.5, 0.6], dtype=float32)>

In [15]:
tf.random.uniform(shape=(2, 2), minval=0.2, maxval= 0.4)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.37396562, 0.28618616],
       [0.3707294 , 0.33582845]], dtype=float32)>

In [16]:
tensor = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


In [17]:
tf.reshape(tensor, [2,6])

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [18]:
tf.reshape(tensor, [12,1])

<tf.Tensor: shape=(12, 1), dtype=float32, numpy=
array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.]], dtype=float32)>

In [19]:
matrix_u = tf.constant([[3,4,3]])
print(matrix_u)
matrix_v = tf.constant([[1,2,1]])
print(matrix_v)
print(tf.matmul(matrix_u, tf.transpose(a=matrix_v)))

tf.Tensor([[3 4 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[1 2 1]], shape=(1, 3), dtype=int32)
tf.Tensor([[14]], shape=(1, 1), dtype=int32)


In [26]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [24]:
tf.rank(tensor)
print("rank is :", tf.rank(tensor).numpy())

rank is : 3


In [25]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [28]:
# 4
tensor[0, 1, 1].numpy()

4.0

In [29]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [30]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[0.02886712 0.48242044]
 [3.0285532  0.5441142 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.39459223 -1.4275445 ]
 [-0.4623587   0.52967066]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.3657251  -0.94512403]
 [ 2.5661945   1.0737848 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.13375485 0.8932594 ]
 [6.5853543  1.1530138 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.6936935   0.38863137]
 [13.016197    2.9264345 ]], shape=(2, 2), dtype=float32)


In [33]:
another_tensor = tf.cast(tensor, dtype='int32')
another_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [34]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


In [35]:
tf.reduce_mean(input_tensor=tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>

In [36]:
tf.reduce_mean(input_tensor=tensor, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[3., 4., 5.],
        [6., 7., 8.]]], dtype=float32)>

In [40]:
tf.Variable(tf.random.uniform(shape=[10, 1], minval=1, maxval=7, dtype=tf.int32))

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[4],
       [1],
       [1],
       [2],
       [5],
       [3],
       [1],
       [1],
       [5],
       [5]])>

In [41]:
dice1 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
# We may add dice1 and dice2 since they share the same shape and size.
dice_sum = dice1 + dice2
# We've got three separate 10x1 matrices. To produce a single
# 10x3 matrix, we'll concatenate them along dimension 1.
resulting_matrix = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
print(resulting_matrix)

tf.Tensor(
[[ 3  4  7]
 [ 4  6 10]
 [ 5  6 11]
 [ 2  1  3]
 [ 5  5 10]
 [ 3  3  6]
 [ 4  1  5]
 [ 3  2  5]
 [ 6  3  9]
 [ 4  6 10]], shape=(10, 3), dtype=int32)


In [42]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint= tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]])>


In [47]:
variable2 = tf.Variable([[0, 1, 2, 3], [3, 4, 5, 6]])
checkpoint = tf.train.Checkpoint(var= variable2)
save_path = checkpoint.save('./vars')
variable2.assign([[4,3,2,1],[1,2,3,4]])
print(variable2)
variable2
checkpoint.restore(save_path)
print(variable2)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[4, 3, 2, 1],
       [1, 2, 3, 4]])>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 1, 2, 3],
       [3, 4, 5, 6]])>


In [48]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

f2 = tf.function(f1)
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == f2(x,y).numpy()
#The assert passes, so there is no output

In [50]:
f2(x,y).numpy()

109.0

In [54]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    print(c)
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.79787034 1.2072097 ]
 [1.197786   1.5210147 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.8580248   0.7160327 ]
 [ 0.02124018 -0.41685525]], shape=(2, 2), dtype=float32)


In [55]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    print(c)
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.77167046 1.4756804 ]
 [0.4422598  1.8155946 ]], shape=(2, 2), dtype=float32)
None


In [57]:
import tensorflow as tf
import tensorflow_datasets as tfds

# Load the CIFAR-10 dataset
dataset, info = tfds.load('cifar10', split='train', as_supervised=True, with_info=True)

# Print the dataset information
print(info)

# Iterate through the dataset
for image, label in dataset.take(5):
    print("Image shape:", image.shape)
    print("Label:", label)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]